### ISSUE TITLE
Test not passing when upgrading org.apache.commons to 1.24

### ISSUE THREAD

**Issue by yildiz-online** [yildiz-online/common-compression#32]
java.lang.NoClassDefFoundError: org/tukaani/xz/FilterOptions
